import type { Meme } from "../types/meme";

/**
 * Realistic dummy meme data that mirrors the Firestore document shape.
 * Heights vary to produce a natural masonry layout.
 */
export const mockMemes: Meme[] = [
  {
    id: "1",
    title: "Distracted Boyfriend",
    image: "https://i.imgflip.com/1ur9b0.jpg",
    height: 320,
    width: 480,
    description: "Guy looking at another girl while his girlfriend watches",
    tags: ["classic", "relationship", "funny"],
    category: "classic",
    templateName: "Distracted Boyfriend",
    language: "en",
    nsfw: false,
    sensitive: false,
    createdAt: new Date("2025-12-01T10:30:00"),
    likeCount: 342,
    shareCount: 128,
    downloadCount: 89,
    popularityScore: 342 * 3 + 128 * 2 + 89,
    storagePath: "memes/distracted-boyfriend.jpg",
    overlay: {
      avatar: "https://api.dicebear.com/9.x/avataaars/svg?seed=Tiffany",
      name: "Tiffany Gleason",
    },
  },
  {
    id: "2",
    title: "Drake Hotline Bling",
    image: "https://i.imgflip.com/30b1gx.jpg",
    height: 380,
    width: 480,
    description: "Drake approving and disapproving",
    tags: ["drake", "approve", "disapprove", "reaction"],
    category: "reaction",
    templateName: "Drake Hotline Bling",
    language: "en",
    nsfw: false,
    sensitive: false,
    createdAt: new Date("2025-11-28T14:20:00"),
    likeCount: 512,
    shareCount: 230,
    downloadCount: 175,
    popularityScore: 512 * 3 + 230 * 2 + 175,
    storagePath: "memes/drake-hotline.jpg",
  },
  {
    id: "3",
    title: "Two Buttons",
    image: "https://i.imgflip.com/1g8my4.jpg",
    height: 420,
    width: 480,
    description: "Sweating over two choices",
    tags: ["choice", "decision", "anxiety", "reaction"],
    category: "reaction",
    templateName: "Two Buttons",
    language: "en",
    nsfw: false,
    sensitive: false,
    createdAt: new Date("2025-11-25T09:00:00"),
    likeCount: 189,
    shareCount: 67,
    downloadCount: 42,
    popularityScore: 189 * 3 + 67 * 2 + 42,
    storagePath: "memes/two-buttons.jpg",
    overlay: {
      avatar: "https://api.dicebear.com/9.x/avataaars/svg?seed=Marcus",
      name: "Marcus Chen",
    },
  },
  {
    id: "4",
    title: "Change My Mind",
    image: "https://i.imgflip.com/24y43o.jpg",
    height: 260,
    width: 480,
    description: "Steven Crowder sitting at a table with a sign",
    tags: ["debate", "opinion", "crowder"],
    category: "opinion",
    templateName: "Change My Mind",
    language: "en",
    nsfw: false,
    sensitive: false,
    createdAt: new Date("2025-11-20T16:45:00"),
    likeCount: 275,
    shareCount: 95,
    downloadCount: 60,
    popularityScore: 275 * 3 + 95 * 2 + 60,
    storagePath: "memes/change-my-mind.jpg",
  },
  {
    id: "5",
    title: "Expanding Brain",
    image: "https://i.imgflip.com/1jwhww.jpg",
    height: 500,
    width: 480,
    description: "Brain expanding through stages of enlightenment",
    tags: ["brain", "intelligence", "levels", "surreal"],
    category: "surreal",
    templateName: "Expanding Brain",
    language: "en",
    nsfw: false,
    sensitive: false,
    createdAt: new Date("2025-11-18T11:15:00"),
    likeCount: 430,
    shareCount: 198,
    downloadCount: 110,
    popularityScore: 430 * 3 + 198 * 2 + 110,
    storagePath: "memes/expanding-brain.jpg",
    overlay: {
      avatar: "https://api.dicebear.com/9.x/avataaars/svg?seed=Sofia",
      name: "Sofia Ramirez",
    },
  },
  {
    id: "6",
    title: "Is This a Pigeon",
    image: "https://i.imgflip.com/1o00in.jpg",
    height: 300,
    width: 480,
    description: "Anime character pointing at butterfly",
    tags: ["anime", "butterfly", "confused"],
    category: "anime",
    templateName: "Is This a Pigeon",
    language: "en",
    nsfw: false,
    sensitive: false,
    createdAt: new Date("2025-11-15T08:30:00"),
    likeCount: 156,
    shareCount: 48,
    downloadCount: 33,
    popularityScore: 156 * 3 + 48 * 2 + 33,
    storagePath: "memes/is-this-pigeon.jpg",
  },
  {
    id: "7",
    title: "Woman Yelling at Cat",
    image: "https://i.imgflip.com/345v97.jpg",
    height: 240,
    width: 480,
    description: "Woman yelling and confused cat at dinner table",
    tags: ["cat", "yelling", "dinner", "funny"],
    category: "animals",
    templateName: "Woman Yelling at Cat",
    language: "en",
    nsfw: false,
    sensitive: false,
    createdAt: new Date("2025-11-12T13:00:00"),
    likeCount: 620,
    shareCount: 310,
    downloadCount: 200,
    popularityScore: 620 * 3 + 310 * 2 + 200,
    storagePath: "memes/woman-yelling-cat.jpg",
    overlay: {
      avatar: "https://api.dicebear.com/9.x/avataaars/svg?seed=Jamal",
      name: "Jamal Wright",
    },
  },
  {
    id: "8",
    title: "One Does Not Simply",
    image: "https://i.imgflip.com/1bij.jpg",
    height: 340,
    width: 480,
    description: "Boromir explains complexity",
    tags: ["lotr", "boromir", "classic"],
    category: "classic",
    templateName: "One Does Not Simply",
    language: "en",
    nsfw: false,
    sensitive: false,
    createdAt: new Date("2025-11-10T17:20:00"),
    likeCount: 388,
    shareCount: 142,
    downloadCount: 95,
    popularityScore: 388 * 3 + 142 * 2 + 95,
    storagePath: "memes/one-does-not.jpg",
  },
  {
    id: "9",
    title: "Surprised Pikachu",
    image: "https://i.imgflip.com/2kbn1e.jpg",
    height: 360,
    width: 480,
    description: "Pikachu with a surprised expression",
    tags: ["pikachu", "pokemon", "surprised", "reaction"],
    category: "reaction",
    templateName: "Surprised Pikachu",
    language: "en",
    nsfw: false,
    sensitive: false,
    createdAt: new Date("2025-11-08T09:45:00"),
    likeCount: 710,
    shareCount: 340,
    downloadCount: 255,
    popularityScore: 710 * 3 + 340 * 2 + 255,
    storagePath: "memes/surprised-pikachu.jpg",
  },
  {
    id: "10",
    title: "Roll Safe Think About It",
    image: "https://i.imgflip.com/1h7in3.jpg",
    height: 280,
    width: 480,
    description: "Guy tapping head with a clever idea",
    tags: ["think", "clever", "smart", "reaction"],
    category: "reaction",
    templateName: "Roll Safe",
    language: "en",
    nsfw: false,
    sensitive: false,
    createdAt: new Date("2025-11-05T12:00:00"),
    likeCount: 245,
    shareCount: 88,
    downloadCount: 52,
    popularityScore: 245 * 3 + 88 * 2 + 52,
    storagePath: "memes/roll-safe.jpg",
    overlay: {
      avatar: "https://api.dicebear.com/9.x/avataaars/svg?seed=Priya",
      name: "Priya Patel",
    },
  },
  {
    id: "11",
    title: "Left Exit 12 Off Ramp",
    image: "https://i.imgflip.com/22bdq6.jpg",
    height: 400,
    width: 480,
    description: "Car swerving to take the exit",
    tags: ["car", "exit", "swerve", "classic"],
    category: "classic",
    templateName: "Left Exit 12 Off Ramp",
    language: "en",
    nsfw: false,
    sensitive: false,
    createdAt: new Date("2025-11-02T15:30:00"),
    likeCount: 167,
    shareCount: 58,
    downloadCount: 39,
    popularityScore: 167 * 3 + 58 * 2 + 39,
    storagePath: "memes/left-exit.jpg",
  },
  {
    id: "12",
    title: "Buff Doge vs Cheems",
    image: "https://i.imgflip.com/43a45p.jpg",
    height: 310,
    width: 480,
    description: "Strong doge compared to weak doge",
    tags: ["doge", "comparison", "dogs", "funny"],
    category: "animals",
    templateName: "Buff Doge vs Cheems",
    language: "en",
    nsfw: false,
    sensitive: false,
    createdAt: new Date("2025-10-30T10:00:00"),
    likeCount: 490,
    shareCount: 215,
    downloadCount: 130,
    popularityScore: 490 * 3 + 215 * 2 + 130,
    storagePath: "memes/buff-doge-cheems.jpg",
    overlay: {
      avatar: "https://api.dicebear.com/9.x/avataaars/svg?seed=Alex",
      name: "Alex Kim",
    },
  },
];
