import type { GalleryItem } from "../data/galleryItems";

/**
 * Realistic dummy meme data that mirrors the Firestore document shape.
 * Heights vary to produce a natural masonry layout.
 */
export const mockMemes: GalleryItem[] = [
  {
    id: 1,
    title: "Distracted Boyfriend",
    image: "https://i.imgflip.com/1ur9b0.jpg",
    height: 320,
    description: "Guy looking at another girl while his girlfriend watches",
    tags: ["classic", "relationship", "funny"],
    category: "classic",
    width: 480,
    uploadedAt: new Date("2025-12-01T10:30:00"),
    storagePath: "memes/distracted-boyfriend.jpg",
    overlay: {
      avatar: "https://api.dicebear.com/9.x/avataaars/svg?seed=Tiffany",
      name: "Tiffany Gleason",
    },
  },
  {
    id: 2,
    title: "Drake Hotline Bling",
    image: "https://i.imgflip.com/30b1gx.jpg",
    height: 380,
    description: "Drake approving and disapproving",
    tags: ["drake", "approve", "disapprove"],
    category: "reaction",
    width: 480,
    uploadedAt: new Date("2025-11-28T14:20:00"),
    storagePath: "memes/drake-hotline.jpg",
  },
  {
    id: 3,
    title: "Two Buttons",
    image: "https://i.imgflip.com/1g8my4.jpg",
    height: 420,
    description: "Sweating over two choices",
    tags: ["choice", "decision", "anxiety"],
    category: "reaction",
    width: 480,
    uploadedAt: new Date("2025-11-25T09:00:00"),
    storagePath: "memes/two-buttons.jpg",
    overlay: {
      avatar: "https://api.dicebear.com/9.x/avataaars/svg?seed=Marcus",
      name: "Marcus Chen",
    },
  },
  {
    id: 4,
    title: "Change My Mind",
    image: "https://i.imgflip.com/24y43o.jpg",
    height: 260,
    description: "Steven Crowder sitting at a table with a sign",
    tags: ["debate", "opinion", "crowder"],
    category: "opinion",
    width: 480,
    uploadedAt: new Date("2025-11-20T16:45:00"),
    storagePath: "memes/change-my-mind.jpg",
  },
  {
    id: 5,
    title: "Expanding Brain",
    image: "https://i.imgflip.com/1jwhww.jpg",
    height: 500,
    description: "Brain expanding through stages of enlightenment",
    tags: ["brain", "intelligence", "levels"],
    category: "surreal",
    width: 480,
    uploadedAt: new Date("2025-11-18T11:15:00"),
    storagePath: "memes/expanding-brain.jpg",
    overlay: {
      avatar: "https://api.dicebear.com/9.x/avataaars/svg?seed=Sofia",
      name: "Sofia Ramirez",
    },
  },
  {
    id: 6,
    title: "Is This a Pigeon",
    image: "https://i.imgflip.com/1o00in.jpg",
    height: 300,
    description: "Anime character pointing at butterfly",
    tags: ["anime", "butterfly", "confused"],
    category: "classic",
    width: 480,
    uploadedAt: new Date("2025-11-15T08:30:00"),
    storagePath: "memes/is-this-pigeon.jpg",
  },
  {
    id: 7,
    title: "Woman Yelling at Cat",
    image: "https://i.imgflip.com/345v97.jpg",
    height: 240,
    description: "Woman yelling and confused cat at dinner table",
    tags: ["cat", "yelling", "dinner"],
    category: "animals",
    width: 480,
    uploadedAt: new Date("2025-11-12T13:00:00"),
    storagePath: "memes/woman-yelling-cat.jpg",
    overlay: {
      avatar: "https://api.dicebear.com/9.x/avataaars/svg?seed=Jamal",
      name: "Jamal Wright",
    },
  },
  {
    id: 8,
    title: "One Does Not Simply",
    image: "https://i.imgflip.com/1bij.jpg",
    height: 340,
    description: "Boromir explains complexity",
    tags: ["lotr", "boromir", "simply"],
    category: "classic",
    width: 480,
    uploadedAt: new Date("2025-11-10T17:20:00"),
    storagePath: "memes/one-does-not.jpg",
  },
  {
    id: 9,
    title: "Surprised Pikachu",
    image: "https://i.imgflip.com/2kbn1e.jpg",
    height: 360,
    description: "Pikachu with a surprised expression",
    tags: ["pikachu", "pokemon", "surprised"],
    category: "reaction",
    width: 480,
    uploadedAt: new Date("2025-11-08T09:45:00"),
    storagePath: "memes/surprised-pikachu.jpg",
  },
  {
    id: 10,
    title: "Roll Safe Think About It",
    image: "https://i.imgflip.com/1h7in3.jpg",
    height: 280,
    description: "Guy tapping head with a clever idea",
    tags: ["think", "clever", "smart"],
    category: "reaction",
    width: 480,
    uploadedAt: new Date("2025-11-05T12:00:00"),
    storagePath: "memes/roll-safe.jpg",
    overlay: {
      avatar: "https://api.dicebear.com/9.x/avataaars/svg?seed=Priya",
      name: "Priya Patel",
    },
  },
  {
    id: 11,
    title: "Left Exit 12 Off Ramp",
    image: "https://i.imgflip.com/22bdq6.jpg",
    height: 400,
    description: "Car swerving to take the exit",
    tags: ["car", "exit", "swerve"],
    category: "classic",
    width: 480,
    uploadedAt: new Date("2025-11-02T15:30:00"),
    storagePath: "memes/left-exit.jpg",
  },
  {
    id: 12,
    title: "Buff Doge vs Cheems",
    image: "https://i.imgflip.com/43a45p.jpg",
    height: 310,
    description: "Strong doge compared to weak doge",
    tags: ["doge", "comparison", "dogs"],
    category: "animals",
    width: 480,
    uploadedAt: new Date("2025-10-30T10:00:00"),
    storagePath: "memes/buff-doge-cheems.jpg",
    overlay: {
      avatar: "https://api.dicebear.com/9.x/avataaars/svg?seed=Alex",
      name: "Alex Kim",
    },
  },
];
